feed page boiler plate
learnwithredwood/amaanytime pull request #10
Opened 2022-12-21 17:45 UTC by iameddieyayaya

![mandatory](https://media1.giphy.com/media/QR7ci2sbhrkzxAuMHH/200.gif?cid=6104955ea9q5tly6uyh6tr2it6wltacyucm9xjpmtazpsgxh&rid=200.gif&ct=g)

2022-12-21 17:52 UTC, iameddieyayaya commented on web/src/components/Icon/Icon.stories.tsx
> +export const Arrow = Template.bind({})
@craineum forgot to clean up this one up; and import only the Icons I am using in the Feed Page.

2022-12-21 17:55 UTC, iameddieyayaya commented on web/src/pages/FeedPage/FeedPage.tsx
> +              <div
@craineum would like to break this into a component <FeedBlock? 
Didn't want to stray too far since, we don't have the schema yet.

2022-12-27 16:27 UTC, craineum reviewed
Some questions and possible changes.

2022-12-27 16:27 UTC, craineum commented on web/src/components/Icon/Icon.stories.tsx
> +export const Arrow = Template.bind({})
@iameddieyayaya Yes, if you could clean up this and the `Icon` component to include what is needed for now.

2022-12-27 16:27 UTC, craineum commented on web/src/components/Icon/Icon.tsx
> +    | 'arrow'
➖ Clean up this list

2022-12-27 16:27 UTC, craineum commented on web/src/index.css
> +@import url('https://fonts.googleapis.com/css2?family=BioRhyme:wght@700;800&family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,700&display=swap');
❓ I don't see in this PR where these CSS classes/styles are being used. Does this need to go in now? Would like to see styling added when we start on the stories in earnest.

2022-12-27 16:27 UTC, craineum commented on web/src/pages/FeedPage/FeedPage.tsx
> +              <div
❓ Can we add the `api` side of things with this PR to make it more of a complete implementation instead of using mock data? Or would that be adding too much to this PR?

To answer your original question, I think if you see a way to improve the code, go for it. I agree that this could be a separate component.

2023-01-04 20:57 UTC, archae0pteryx commented
I just learned today that there's some tricky svg bits when rendering svgs like these. I guess you're not supposed to use viewBox and some other stuff... I haven't dove into it but while i'm thinking about it, it might be worth optimizing these svgs with an external tool. I think there's a bunch out there that are web based.

2023-01-06 21:50 UTC, craineum commented
> I just learned today that there's some tricky svg bits when rendering svgs like these. I guess you're not supposed to use viewBox and some other stuff... I haven't dove into it but while i'm thinking about it, it might be worth optimizing these svgs with an external tool. I think there's a bunch out there that are web based.

@ahaywood would you have thoughts on this?

2023-01-06 22:09 UTC, craineum requested changes
Looking great! Some comments and changes to follow up on.

2023-01-06 22:09 UTC, craineum commented on web/src/pages/FeedPage/FeedPage.tsx
> +export const QUERY = gql`
♻️ I think the `FeedPage` should be pretty "dumb" and there should be a component `Cell` whose job it is to query this data.

2023-01-06 22:09 UTC, craineum commented on web/src/pages/FeedPage/FeedPage.tsx
> +      {isAuthenticated ? (
➖ If we put this page behind an authenticated route, then this wouldn't be needed.

2023-01-06 22:09 UTC, craineum commented on web/src/lib/formatters.test.tsx
> +    // @ts-expect-error - Testing JS scenario
❓ This is strange, is there not another way around this?

2023-01-06 22:09 UTC, craineum commented on web/src/lib/formatters.tsx
> +  return <input type="checkbox" checked={checked} disabled />
❓ Was this file created from the generator or from Amy's original code? Just some funny stuff here. Like this isn't really an input, it is more a checkbox display of a value.

2023-01-09 18:42 UTC, iameddieyayaya commented on web/src/lib/formatters.tsx
> +  return <input type="checkbox" checked={checked} disabled />
Grab it from Amy's repo.

2023-01-09 19:47 UTC, iameddieyayaya commented on web/src/lib/formatters.tsx
> +  return <input type="checkbox" checked={checked} disabled />
^ Actually might be a RW generated thing its, all over the repo.

For example;
https://github.com/learnwithredwood/amaanytime/blob/main/web/src/components/Admin/Team/Team/Team.tsx#L23

2023-01-09 20:29 UTC, craineum requested changes
Couple more minor things, then I think we are good to go!

2023-01-09 20:29 UTC, craineum commented on api/src/services/questions/questions.ts
> +  votes: (_obj, { root }) => {
♻️ Some of these should maybe be commented out or removed as well.

2023-01-09 20:29 UTC, craineum commented on web/src/Routes.tsx
> +      <Set wrap={MainLayout}>
♻️ This should probably be behind the admin section.

2023-01-09 20:29 UTC, craineum commented on web/src/lib/formatters.tsx
> +  return <input type="checkbox" checked={checked} disabled />
Yeah, okay, let's keep it then for now.

2023-01-09 22:29 UTC, iameddieyayaya commented on api/src/services/questions/questions.ts
> +  votes: (_obj, { root }) => {
good catch! Let me do that.

2023-01-10 17:29 UTC, craineum approved these changes
LGTM 🚀

2023-01-10 17:29 UTC, merged