Styling/loginpage
learnwithredwood/amaanytime pull request #11
Opened 2023-01-03 15:35 UTC by nataliadiaz2

# Pull Request

## Description

Styling for Login Page

## Solution

Describe your code changes in detail for reviewers.

## Screenshots

![Screenshot 2023-01-03 at 7 33 30 AM](https://user-images.githubusercontent.com/101531284/210389271-878e5bb6-7af4-4c86-9868-fe3408d9ec3e.png)

![Screenshot 2023-01-03 at 7 32 53 AM](https://user-images.githubusercontent.com/101531284/210389162-a765ba58-336e-49eb-b657-2d7e8443a239.png)

![Screenshot 2023-01-03 at 7 31 50 AM](https://user-images.githubusercontent.com/101531284/210389064-81138d77-55f9-4a22-a9aa-6c784fca33ff.png)

## Affected Areas

Login Page

## Tests

Describe the tests.

## Was this feature tested on all browsers?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Related PRs

Add any related pull requests

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/8Iv5lqKwKsZ2g/giphy.gif)

2023-01-05 14:48 UTC, craineum requested changes
Besides the minor things commented on, ➕ we are missing the dark background at full screen.

Let's work together on the broken test as well.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.mocks.ts
> +  label: 'my field',
♻️ Reuse the minimum where possible with ` ...minimum`.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.test.tsx
> +// testing validation is handled at the form level
➖ Probably don't need these comments.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.test.tsx
> +  // actual string validation is handled through TypeScript, this is just to
➖ I think this comment is more confusing than anything. The test description seems like enough.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.test.tsx
> +  it('can handle a placeholder value', () => {
➕ Be consistent with spacing, I like the line space between tests like above.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.tsx
> +const AmaTextField = forwardRef((props: AmaTextFieldProps, ref: any) => {
♻️ I know we are still trying to resolve this functionality, but the at the end we shouldn't be using `any` as a type def.

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.tsx
> +  const register = useRegister({
❓ When using a passed in reference, we might need to re-think using `useRegister`, maybe?

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.tsx
> +    className: ``,
❓ Hmm.... it feels like this shouldn't be empty?

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/AmaTextField.tsx
> +    errorClassName: `rw-label rw-label-error`,
❓ Surprised we are using Redwood styling classes. Did we modify them?

2023-01-05 14:48 UTC, craineum commented on web/src/components/AmaTextField/index.tsx
> +export { AmaTextField } from './AmaTextField'
❓ Do we need this file? Kinda goes against the Redwood component pattern.

2023-01-05 14:48 UTC, craineum commented on web/src/components/SearchInput/index.ts
> +export { SearchInput } from './SearchInput'
➖ Can we remove this?

2023-01-05 14:48 UTC, craineum commented on web/src/index.css
> +  /* CUSTOM CHECKBOX */
➖ Remove comments with nothing below them.

2023-01-12 00:06 UTC, archae0pteryx commented on web/src/components/SearchInput/index.ts
> +export { SearchInput } from './SearchInput'
Do you prefer the `component/ThisComponent/ThisComponent` pattern? I have been updating these when i touch them like this so that i can do cleaner imports - especially when there's more than one export. `component/ThisComponent` feels better to me but i don't mind reverting the ones i've changed?

2023-01-12 21:54 UTC, archae0pteryx commented
Replaced by #15 

Theres prob some little things here and there but we should just get the bulk in and divide into smaller chunks. One thing for sure is the auto focus still. I made a ticket for this already.

2023-01-20 21:06 UTC, closed without merging