✨ Feat/profile
learnwithredwood/amaanytime pull request #19
Opened 2023-01-19 21:31 UTC by nataliadiaz2

# Pull Request

## Story

Feature Edit Profile

## Description

Edit Profile form update, add profile elements, add styling to form 

## Analysis and Design

[Figma](https://www.figma.com/file/71cvT12tjZmTiwg6nRyuJb/AMA-Anytime?node-id=538%3A9757&t=XyaG0dPcvSwdUBJ4-0)
## Solution

Schema User update, GraphQL Profile update, Edit Profile update, 

## Screenshots

## Affected Areas

User Table, Profile GraphQL, Edit Profile component

## Tests

Rendering correctly 

## Was this feature tested on all browsers?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/l0amJzVHIAfl7jMDos/giphy.gif)

2023-01-20 21:10 UTC, archae0pteryx commented on web/src/components/Avatar/Avatar.test.tsx
> +    render(<Avatar {...AvatarNoImage} />)
I think these can all just be 2 tests. At least the tests that pass the same props (avatarNoImage) can all have their assertions in a single, "It renders default configuration / avatar / whatever". You can assert / expect more than one thing in a test if you wanna. Just a thought.

2023-01-20 21:12 UTC, archae0pteryx commented on web/src/components/Avatar/Avatar.tsx
> +  | 'GRAY'
exactly what an enum is for.

2023-01-20 21:17 UTC, archae0pteryx reviewed
LGTM.

2023-01-24 17:13 UTC, craineum requested changes
Looking good, some things to clean-up.

2023-01-24 17:13 UTC, craineum commented on web/src/components/Avatar/Avatar.tsx
> +            avatarColor || 'PUNCH'
♻️ Instead defaulting to one of the items, this should maybe be a separate utility function that gets passed a string (name) and selects a color based on that name. That way you could also use the same thing for the cover background color.

2023-01-25 13:12 UTC, craineum requested changes

2023-01-25 13:12 UTC, craineum commented on web/src/components/Profile/EditProfileCell/EditProfileCell.tsx
> +          profile.username || profile.name || profile.email
♻️ Maybe this name selection process should be a utility function as well.

2023-01-25 13:12 UTC, craineum commented on web/src/components/Profile/EditProfile/EditProfile.tsx
> +            src="https://i.picsum.photos/id/237/750/295.jpg?hmac=G-dedeDLqcYUvDe-WUKTnnGIhDo6Kz5rzRwp-y6wgd4"
💬 Let's pair on these utility functions today.

2023-01-25 19:51 UTC, craineum approved these changes
One final tweak and it looks good to go!

2023-01-25 19:51 UTC, craineum commented on web/src/utils/UserHelpers.ts
> +  return colors[letterNumber % 7]
♻️ Change the `7` to the length of colors.

2023-01-25 20:29 UTC, merged