✨ Navigation Styling
learnwithredwood/amaanytime pull request #21
Opened 2023-01-30 23:14 UTC by nataliadiaz2

# Pull Request

## Description

Navigation Styling 

## Analysis and Design

[Link to mobile design](https://www.figma.com/file/71cvT12tjZmTiwg6nRyuJb/AMA-Anytime?node-id=328%3A6435&t=cIMrB1JjiYKH2ptp-1)
[Link to desktop design](https://www.figma.com/file/71cvT12tjZmTiwg6nRyuJb/AMA-Anytime?node-id=204%3A5751&t=7t3buf69Rr6rc9ZH-1)

## Solution

Update Navigation Component 

## Screenshots

![Screenshot 2023-01-30 at 3 11 23 PM](https://user-images.githubusercontent.com/101531284/215617543-48eb6b02-2a82-4a15-a07e-2045908b300a.png)

![Screenshot 2023-01-30 at 3 12 15 PM](https://user-images.githubusercontent.com/101531284/215617640-8164c96b-8e05-4869-9283-fb373565dc81.png)

## Affected Areas

Navigation

## Was this feature tested on all browsers?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/MZocLC5dJprPTcrm65/giphy.gif)

2023-01-31 12:47 UTC, craineum requested changes
Looking good a few things to clean up.

2023-01-31 12:47 UTC, craineum commented on web/src/components/Navigation/AvatarMenu/AvatarMenu.tsx
> +        <Avatar
♻️ It would be better if this isn't a part of the menu, and that the menu shows below the current avatar in the header bar.

2023-01-31 12:47 UTC, craineum commented on web/src/components/Navigation/AvatarMenu/AvatarMenu.tsx
> +          <div className="cursor-pointer">
⚠️ The logout should be pinned at the bottom of the screen.

2023-01-31 12:47 UTC, craineum commented on web/src/components/Navigation/AvatarMenu/AvatarMenu.tsx
> +      <div className="cursor-pointer">
♻️ Add some kind of visual divider between the items above and logout. Like the break between the name and the menu on the mobile version.

2023-01-31 12:47 UTC, craineum commented on web/src/components/Navigation/Navigation.test.tsx
> +import { render, screen } from '@redwoodjs/testing/web'
❓ Why were all the tests removed?

2023-01-31 19:13 UTC, nataliadiaz2 commented on web/src/components/Navigation/Navigation.test.tsx
> +import { render, screen } from '@redwoodjs/testing/web'
I’m tried to mock out the screen size to test, I'll keep looking into that.

2023-02-07 16:09 UTC, craineum approved these changes
Couple of very minor things, looks good!

2023-02-07 16:09 UTC, craineum commented on web/src/components/Navigation/AvatarMenu/AvatarMenu.tsx
> +    <>
🔥 Probably don't need the fragment tags here.

2023-02-07 16:09 UTC, craineum commented on web/src/layouts/ProfileLayout/ProfileLayout.tsx
> +        <SubNavigation className={''}>
🔥 Can remove this.

2023-02-07 20:32 UTC, craineum approved these changes
LGTM 🚀

2023-02-07 20:32 UTC, merged